const products = [
  {
    id: 1,
    name: "Wine - Saint Emilion Calvet",
    image: "http://dummyimage.com/x.png/ff4444/ffffff",
    description: "Debrid opn fx-femur",
    brand: "Hydrocortisone Acetate",
    category: "Granite Surfaces",
    price: "$487.30",
    countInStock: 765,
    rating: 4,
    numReviews: 126,
  },
  {
    id: 2,
    name: "Lobster - Baby, Boiled",
    image: "http://dummyimage.com/x.png/cc0000/ffffff",
    description: "Esophagectomy NOS",
    brand: "Topcare hemorrhoidal",
    category: "Structural & Misc Steel Erection",
    price: "$121.65",
    countInStock: 370,
    rating: 1,
    numReviews: 68,
  },
  {
    id: 3,
    name: "Chocolate - Milk Coating",
    image: "http://dummyimage.com/x.png/ff4444/ffffff",
    description: "Esophagostomy NOS",
    brand: "Aromafields Tiger Lily Scented Antibacterial Hand Wash",
    category: "HVAC",
    price: "$715.45",
    countInStock: 228,
    rating: 2,
    numReviews: 833,
  },
  {
    id: 4,
    name: "Wine - Cahors Ac 2000, Clos",
    image: "http://dummyimage.com/x.png/5fa2dd/ffffff",
    description: "Limb lengthn-metatar/tar",
    brand: "Brevibloc",
    category: "Hard Tile & Stone",
    price: "$976.32",
    countInStock: 932,
    rating: 1,
    numReviews: 966,
  },
  {
    id: 5,
    name: "Sugar - Sweet N Low, Individual",
    image: "http://dummyimage.com/x.png/dddddd/000000",
    description: "Total patellectomy",
    brand: "CVS ANTI ITCH",
    category: "Masonry",
    price: "$865.78",
    countInStock: 39,
    rating: 2,
    numReviews: 32,
  },
  {
    id: 6,
    name: "Coke - Classic, 355 Ml",
    image: "http://dummyimage.com/x.png/5fa2dd/ffffff",
    description: "Rt & lt heart angiocard",
    brand: "Tinaacide Athletes Foot",
    category: "Structural and Misc Steel (Fabrication)",
    price: "$789.48",
    countInStock: 941,
    rating: 3,
    numReviews: 435,
  },
  {
    id: 7,
    name: "Coriander - Seed",
    image: "http://dummyimage.com/x.png/5fa2dd/ffffff",
    description: "Postop vasc op hem contr",
    brand: "Omnaris",
    category: "Epoxy Flooring",
    price: "$920.77",
    countInStock: 824,
    rating: 0,
    numReviews: 819,
  },
  {
    id: 8,
    name: "Bread - Pita",
    image: "http://dummyimage.com/x.png/dddddd/000000",
    description: "Fit above knee prosthes",
    brand: "QUITA COLICOS GAS RELIEF DROPS",
    category: "Prefabricated Aluminum Metal Canopies",
    price: "$244.92",
    countInStock: 334,
    rating: 1,
    numReviews: 65,
  },
  {
    id: 9,
    name: "Stock - Chicken, White",
    image: "http://dummyimage.com/x.png/dddddd/000000",
    description: "Refusion of atlas-axis",
    brand: "Allopurinol",
    category: "Temp Fencing, Decorative Fencing and Gates",
    price: "$691.99",
    countInStock: 822,
    rating: 1,
    numReviews: 118,
  },
  {
    id: 10,
    name: "Table Cloth 53x69 White",
    image: "http://dummyimage.com/x.png/cc0000/ffffff",
    description: "Open biopsy of esophagus",
    brand: "FIBROMYALGIA HP",
    category: "Rebar & Wire Mesh Install",
    price: "$754.22",
    countInStock: 498,
    rating: 3,
    numReviews: 935,
  },
];

export default products
